const { chromium } = require(process.argv[2] || 'playwright');
const assert = require('node:assert/strict');
const { revealStory, optionAction } = require('./story-helpers.cjs');
const path = require('node:path');
let browser;
(async () => {
  browser = await chromium.launch({ headless: true, executablePath: process.argv[3] });
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  let release;
  const gate = new Promise(resolve => { release = resolve; });
  await page.route('**/*.png', async route => { await gate; await route.continue(); });
  await page.goto(process.argv[4] || 'http://127.0.0.1:5173/', { waitUntil: 'domcontentloaded' });
  await page.waitForSelector('#loading-screen');
  assert.equal(await page.locator('#start-button').isVisible(), false);
  assert.equal(await page.locator('#interface').isVisible(), false);
  await page.screenshot({ path: path.resolve('artifacts/loading.png') });
  release();
  await page.waitForSelector('#start-button:enabled');
  await page.screenshot({ path: path.resolve('artifacts/title.png') });
  await page.keyboard.press('KeyR');
  assert.equal(await page.locator('body').getAttribute('data-mode'), 'title');
  await page.setViewportSize({ width: 390, height: 740 });
  await page.screenshot({ path: path.resolve('artifacts/title-narrow.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.locator('#start-button').click();
  await page.waitForFunction(() => document.body.dataset.mode === 'story');
  assert.match(await page.locator('#scene-background').getAttribute('src'), /intro.*\.png/);
  assert.equal(await page.locator('#chapter-label').textContent(), 'THE JOURNEY BEGINS');
  await page.waitForTimeout(300);
  const partial = await page.locator('#story-text').textContent();
  assert.ok(partial.length > 0 && partial.length < 100, 'Intro uses the narrator typewriter');
  await page.locator('#scene-background').click({ position: { x: 20, y: 20 } });
  await page.keyboard.press('Space');
  await page.keyboard.press('KeyR');
  assert.equal(await page.locator('body').getAttribute('data-mode'), 'story');
  assert.equal(await page.locator('#ammo').textContent(), '0');
  assert.equal(await page.locator('#clock').textContent(), '00:00');
  assert.match(await revealStory(page), /light every totem/);
  assert.equal(await page.evaluate(() => {
    const box = document.querySelector('#story-scene').getBoundingClientRect();
    return box.top >= 0 && box.bottom <= innerHeight;
  }), true, 'The complete introduction fits on a narrow screen');
  await page.screenshot({ path: path.resolve('artifacts/intro-narrow.png') });
  await page.locator('#story-next').click();
  await page.waitForFunction(() => document.body.dataset.mode === 'playing');
  assert.equal(await page.locator('#ammo').textContent(), '0');
  assert.equal(await page.locator('#cinematics').isVisible(), false);
  const { levels } = await import('../src/levels.js');
  await page.evaluate(ids => localStorage.setItem('zeus-progress-v1', JSON.stringify({ stars: Object.fromEntries(ids.map(id => [id, 3])), muted: true })), levels.map(level => level.id));
  await page.reload();
  await page.waitForSelector('#start-button:enabled');
  await page.locator('#start-button').click();
  await page.waitForFunction(() => document.body.dataset.mode === 'playing');
  await page.setViewportSize({ width: 1280, height: 800 });
    await optionAction(page, 'home');
    await page.waitForFunction(() => document.body.dataset.mode === 'title');
    await page.locator('#levels-button').click();
    await page.locator('[data-level="4"]').click();
    await page.waitForFunction(() => document.body.dataset.mode === 'playing');
  await page.waitForTimeout(100);
  const point = await page.evaluate(() => {
    const box = document.querySelector('#game canvas').getBoundingClientRect();
    const scale = Math.max(8, Math.min((box.width - 44) / 16.5, (box.height - 310) / 8.5));
    return { x: box.x + box.width / 2 - scale, y: box.y + box.height / 2 + 1.6 * scale };
  });
  await page.mouse.move(point.x, point.y);
  await page.waitForTimeout(50);
  await page.keyboard.press('Space');
  await page.waitForFunction(() => document.body.dataset.mode === 'story');
  await page.setViewportSize({ width: 390, height: 740 });
  await revealStory(page);
  assert.equal(await page.evaluate(() => {
    const box = document.querySelector('#story-scene').getBoundingClientRect();
    const goat = document.querySelector('.narrator').getBoundingClientRect();
    const text = document.querySelector('#story-text').getBoundingClientRect();
    return box.top >= 0 && box.bottom <= innerHeight && goat.right <= text.left;
  }), true, 'The narrator and complete story must fit a narrow screen');
  await page.screenshot({ path: path.resolve('artifacts/story-narrow.png') });
  // Failed assets must leave a visible retry rather than starting an incomplete game.
  await page.unroute('**/*.png');
  await page.route('**/*title*.png', route => route.abort());
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.waitForSelector('#loading-retry');
  assert.equal(await page.locator('#start-button').isVisible(), false);
  await page.unroute('**/*title*.png');
  await page.locator('#loading-retry').click();
  await page.waitForSelector('#start-button:enabled');
  assert.deepEqual(errors, []);
  console.log('Cinematics check passed: loading gate, title, narrow title/story layouts, Start, input isolation and asset retry.');
  await browser.close();
})().catch(async error => { console.error(error); await browser?.close(); process.exitCode = 1; });
