// Eagle training continues the existing campaign without changing saved IDs.
export function advancedLevels(board) {
  const wall = (x, ys) => ys.map(y => ['#', x, y]);
  const mirror = (x, y, angle, rotatable = false) => ({ x, y, angle, rotatable });
  const up = Math.PI / 4, down = -Math.PI / 4;
  return [
    {
      id: 'spirit-four-turns', name: 'Four Turns, One Will', lesson: '26 · UNIFY THE PATH',
      hint: 'Set both blue mirrors. Four turns carry one bolt into the cyclic cloud.',
      mentor: '“Let every turn serve the same intention.” — The Eagle',
      shots: 3, idealShots: 1, threeStarTime: 90,
      map: board([['Z', -5, -2.5], ['m', -2, -2.5], ['/', -2, 1.5], ['m', 2, 1.5], ['/', 2, -1.5], ['N', 5, -1.5], ['T', 5, 1.5], ['D', 6, 2.5],
        ...wall(0, [-2.5, -.5, .5, 2.5])]),
      mirrors: [mirror(-2, -2.5, .1, true), mirror(-2, 1.5, up), mirror(2, 1.5, .2, true), mirror(2, -1.5, down)],
      clouds: [{ x: 5, y: -1.5, period: 4, direction: { x: 0, y: 1 } }],
    },
    {
      id: 'spirit-balanced-echoes', name: 'Three Echoes in Balance', lesson: '27 · BALANCE THE RELEASES',
      hint: 'Burn the crate, then split after two bounces. Both cloud paths must arrive together.',
      mentor: '“Patience gives two distant echoes one heartbeat.” — The Eagle',
      shots: 4, idealShots: 2, threeStarTime: 100,
      map: board([['Z', -5, -2.5], ['m', -2, -2.5], ['W', -2, -1.5], ['/', -2, .5], ['G', 1, .5], ['N', 4, .5], ['N', 1, 2.5], ['T', 4, -2.5], ['T', 5, 2.5], ['D', 6, 1.5],
        ...wall(0, [-2.5, -1.5, -.5, 1.5, 2.5])]),
      mirrors: [mirror(-2, -2.5, .1, true), mirror(-2, .5, up)],
      crystals: [{ x: 1, y: .5, period: 10, phase: up - Math.PI / 10 * (1 + 8.58 / 12) }],
      clouds: [{ x: 4, y: .5, delay: .9, direction: { x: 0, y: -1 } }, { x: 1, y: 2.5, delay: 1, direction: { x: 1, y: 0 } }],
      totems: [{ x: 4, y: -2.5, group: 'balance' }, { x: 5, y: 2.5, group: 'balance' }],
      groups: [{ id: 'balance', type: 'timed', window: .35 }],
    },
    {
      id: 'spirit-conducting-maze', name: 'The Conducting Labyrinth', lesson: '28 · PREPARE AND RETURN',
      hint: 'Burn and break. Park the return mirror flat, then turn it during the cloud charge.',
      mentor: '“Prepare the return before the sky answers.” — The Eagle',
      shots: 5, idealShots: 4, threeStarTime: 110,
      map: board([['Z', -5, -1.5], ['W', -3, -1.5], ['m', -2, -1.5], ['B', -1, -1.5], ['m', 1, -1.5], ['=', 1, .5], ['=', 1, 1.5], ['=', 2, 1.5], ['=', 3, 1.5], ['N', 4, 1.5], ['/', 4, -1.5], ['T', -2, 2.5], ['D', 6, 2.5], ['#', -4, .5], ['#', -3, 1.5],
        ...wall(0, [.5, 1.5, 2.5])]),
      mirrors: [mirror(-2, -1.5, .1, true), mirror(1, -1.5, .1, true), mirror(4, -1.5, up)],
      metalPorts: [{ x: 3, y: 1.5, direction: { x: 1, y: 0 } }],
      clouds: [{ x: 4, y: 1.5, period: 6, direction: { x: 0, y: -1 } }],
    },
    {
      id: 'spirit-two-horizons', name: 'One Mirror, Two Horizons', lesson: '29 · ORDER THE RELEASES',
      hint: 'Clear the crate. Use the far blue mirror to visit totems 1 then 2 on separate releases.',
      mentor: '“A steady spirit can choose a new horizon.” — The Eagle',
      shots: 4, idealShots: 3, threeStarTime: 110,
      map: board([['Z', -5, -1.5], ['/', -2, -1.5], ['W', -2, .5], ['N', -2, 1.5], ['m', 3, 1.5], ['T', 3, -1.5], ['T', 5, -.5], ['D', 6, 2.5],
        ...wall(0, [-2.5, -1.5, -.5, .5, 2.5])]),
      mirrors: [mirror(-2, -1.5, up), mirror(3, 1.5, .1, true)],
      clouds: [{ x: -2, y: 1.5, period: 4, direction: { x: 1, y: 0 } }],
      totems: [{ x: 3, y: -1.5, group: 'horizons', order: 1 }, { x: 5, y: -.5, group: 'horizons', order: 2 }],
      groups: [{ id: 'horizons', type: 'ordered' }],
    },
    {
      id: 'spirit-storm', name: 'The Spirit and the Storm', lesson: '30 · MASTER THE TWO CLOCKS',
      hint: 'Open the breach. A release at 6 s must split into two paths within a 1.05 s window.',
      mentor: '“Your spirit must hold the whole storm at once.” — The Eagle',
      shots: 5, idealShots: 4, threeStarTime: 120,
      map: board([['Z', -5, -1.5], ['W', -3, -1.5], ['B', -1, -1.5], ['m', 1, -1.5], ['=', 1, .5], ['=', 1, 1.5], ['=', 2, 1.5], ['=', 3, 1.5], ['N', 4, 1.5], ['G', 4, -.5], ['T', 4, -2.5], ['m', -4, -.5], ['/', -4, 2.5], ['T', -1, 2.5], ['D', 6, 2.5], ['#', -2, 1.5],
        ...wall(0, [-2.5, .5, 2.5])]),
      mirrors: [mirror(1, -1.5, .1, true), mirror(-4, -.5, .1, true), mirror(-4, 2.5, up)],
      metalPorts: [{ x: 3, y: 1.5, direction: { x: 1, y: 0 } }],
      clouds: [{ x: 4, y: 1.5, period: 6, direction: { x: 0, y: -1 } }],
      crystals: [{ x: 4, y: -.5, period: 8, phase: up - Math.PI / 8 * (6 + 1.09995 / 12), incoming: { x: 0, y: -1 } }],
      totems: [{ x: 4, y: -2.5, group: 'spirit' }, { x: -1, y: 2.5, group: 'spirit' }],
      groups: [{ id: 'spirit', type: 'timed', window: 1.05 }],
    },
    {
      id: 'guardian-back', name: "The Guardian's Back", lesson: '31 · STRIKE FROM BEHIND',
      hint: 'Three bounces cross the patrol. Strike its back, then send another bolt through the breach.',
      mentor: '“Its front absorbs your power. Its back reveals its weakness.” — The Eagle',
      shots: 3, idealShots: 2, threeStarTime: 110,
      map: board([['Z', -5, -1.5], ['m', -2, -1.5], ['N', -2, .5], ['/', -2, 1.5], ['m', 3, 1.5], ['T', 3, -1.5], ['D', 6, 2.5],
        ...wall(0, [-2.5, -1.5, -.5, .5, 2.5])]),
      mirrors: [mirror(-2, -1.5, .1, true), mirror(-2, 1.5, up), mirror(3, 1.5, .1, true)],
      clouds: [{ x: -2, y: .5, delay: .8, direction: { x: 0, y: 1 } }],
      monsters: [{ from: -1, to: 2, y: 1.5, speed: 1, phase: 3 }],
    },
    {
      id: 'guardian-order', name: 'Two Watchers, One Order', lesson: '32 · READ BOTH PATROLS',
      hint: 'Open each guarded corridor from behind. Activate the upper totem before the lower one.',
      mentor: '“Two patrols. Two rhythms. One unwavering intention.” — The Eagle',
      shots: 5, idealShots: 4, threeStarTime: 120,
      map: board([['Z', -5, -.5], ['m', -2, -.5], ['/', -2, 1.5], ['/', -2, -1.5], ['T', 5, 1.5], ['T', 5, -1.5], ['D', 6, 2.5],
        ...wall(0, [-2.5, -.5, .5, 2.5])]),
      mirrors: [mirror(-2, -.5, .1, true), mirror(-2, 1.5, up), mirror(-2, -1.5, down)],
      monsters: [{ from: -1, to: 2, y: 1.5, speed: 1.2, phase: 2 }, { from: -1, to: 2, y: -1.5, speed: 1, phase: 4 }],
      totems: [{ x: 5, y: 1.5, group: 'watchers', order: 1 }, { x: 5, y: -1.5, group: 'watchers', order: 2 }],
      groups: [{ id: 'watchers', type: 'ordered' }],
    },
    {
      id: 'guardian-relay', name: 'The Storm Behind the Guard', lesson: '33 · TIME THE RETURN',
      hint: 'Clear the crate. The cloud relay must return while the guardian walks left, exposing its back.',
      mentor: '“Aim for where the guardian will be when the sky answers.” — The Eagle',
      shots: 4, idealShots: 3, threeStarTime: 120,
      map: board([['Z', -6, -2.5], ['m', -4, -2.5], ['W', -4, -.5], ['m', -4, 1.5], ['/', 1, 1.5], ['N', 1, -1.5], ['N', 5, -1.5], ['/', 5, 1.5], ['T', 1, 2.5], ['D', 6, 2.5], ['#', -5, -.5], ['#', 2, 2.5],
        ...[-2, -1, 0].flatMap(x => [['#', x, 2.5], ['#', x, .5]]),
        ...wall(-3, [-2.5, -1.5, -.5, .5, 2.5]), ...wall(3, [-2.5, -.5, .5, 2.5])]),
      mirrors: [mirror(-4, -2.5, .1, true), mirror(-4, 1.5, .1, true), mirror(1, 1.5, down), mirror(5, 1.5, down)],
      clouds: [{ x: 1, y: -1.5, period: 4, direction: { x: 1, y: 0 } }, { x: 5, y: -1.5, period: 4, phase: 2, direction: { x: 0, y: 1 } }],
      monsters: [{ from: 1.8, to: 4.2, y: 1.5, speed: .8, phase: 0 }],
    },
    {
      id: 'guardian-twin-gates', name: 'Twin Gates of Stone', lesson: '34 · SPLIT AND SHATTER',
      hint: 'Burn the crate. Split toward both backs, then repeat the split to synchronize the totems.',
      mentor: '“The same spark must hold two weaknesses and two destinations.” — The Eagle',
      shots: 4, idealShots: 3, threeStarTime: 120,
      map: board([['Z', -5, -.5], ['W', -3, -.5], ['G', -2, -.5], ['N', -2, 1.5], ['T', 5, -.5], ['T', 5, 1.5], ['D', 6, 2.5], ['#', -1, .5]]),
      mirrors: [],
      crystals: [{ x: -2, y: -.5, period: 4, phase: up - Math.PI / 4 * (1 + 2.58 / 12) }],
      clouds: [{ x: -2, y: 1.5, delay: 1.8, direction: { x: 1, y: 0 } }],
      monsters: [{ from: 0, to: 2, y: -.5, speed: .5, phase: 0 }, { from: 0, to: 2, y: 1.5, speed: .5, phase: 0 }],
      totems: [{ x: 5, y: -.5, group: 'gates' }, { x: 5, y: 1.5, group: 'gates' }],
      groups: [{ id: 'gates', type: 'timed', window: 2.05 }],
    },
    {
      id: 'one-with-thunder', name: 'One with the Thunder', lesson: '35 · THE FINAL TRIAL',
      hint: 'Open the breach. Dodge the crossing patrol, shatter the returning guard, then unify both branches.',
      mentor: '“Become the thunder, Zeus. The Titans will offer no second lesson.” — The Eagle',
      shots: 6, idealShots: 5, threeStarTime: 150,
      map: board([['Z', -5, -1.5], ['W', -3, -1.5], ['B', -1, -1.5], ['m', 1, -1.5], ['=', 1, .5], ['=', 1, 1.5], ['=', 2, 1.5], ['=', 3, 1.5], ['N', 4, 1.5], ['G', 4, -.5], ['T', 4, -2.5], ['m', -4, -.5], ['/', -4, 2.5], ['T', -1, 2.5], ['D', 6, 2.5], ['#', -2, 1.5],
        ...wall(0, [-2.5, .5, 2.5])]),
      mirrors: [mirror(1, -1.5, .1, true), mirror(-4, -.5, .1, true), mirror(-4, 2.5, up)],
      metalPorts: [{ x: 3, y: 1.5, direction: { x: 1, y: 0 } }],
      clouds: [{ x: 4, y: 1.5, period: 8, direction: { x: 0, y: -1 } }],
      crystals: [{ x: 4, y: -.5, period: 8, phase: up - Math.PI / 8 * (8 + 1.09995 / 12), incoming: { x: 0, y: -1 } }],
      monsters: [{ from: 3, to: 5, y: -1.5, speed: .5, phase: 0 }, { from: -2, to: 1, y: -.5, speed: .75, phase: 4 }],
      totems: [{ x: 4, y: -2.5, group: 'unity' }, { x: -1, y: 2.5, group: 'unity' }],
      groups: [{ id: 'unity', type: 'timed', window: 1.05 }],
    },
  ];
}
