import { advancedLevels } from './advanced-levels.js';
// ASCII lays out cells; metadata supplies arbitrary mirror angles.
function board(placements) {
  const cells = Array.from({ length: 8 }, (_, row) =>
    Array.from({ length: 15 }, (_, col) => row === 0 || row === 7 || col === 0 || col === 14 ? '#' : '.'));
  for (const [symbol, x, y] of placements) cells[Math.round(3.5 - y)][x + 7] = symbol;
  return cells.map(row => row.join(''));
}

export const levels = [
  {
    id: 'first-spark', name: 'The First Spark', lesson: '01 · AIM',
    hint: 'Aim at the totem and fire. Lightning takes time to reach its target.',
    mentor: '“Even the greatest thunder begins with a spark.”',
    idealShots: 1, threeStarTime: 30,
    map: board([['Z', -5, -1.5], ['T', 4, 1.5], ['D', 6, 2.5], ['#', -1, -2.5], ['#', 2, -.5]]),
    mirrors: [],
  },
  {
    id: 'bronze', name: 'The Secret of Bronze', lesson: '02 · REFLECT',
    hint: 'The wall blocks the direct path. Aim at the center of the bronze mirror.',
    mentor: '“The shortest path is not always the way forward.”',
    idealShots: 1, threeStarTime: 45,
    map: board([['Z', -5, -1.5], ['T', -1, 2.5], ['D', 6, 2.5], ['/', -1, -1.5], ['#', -3, .5], ['#', -3, 1.5], ['#', 1, -1.5]]),
    mirrors: [{ x: -1, y: -1.5, angle: Math.PI / 4, rotatable: false }],
  },
  {
    id: 'turn', name: 'A New Direction', lesson: '03 · ROTATE',
    hint: 'Drag the blue mirror to angle it toward the totem. Then aim at its center and press Space.',
    mentor: '“Your hands choose the direction. Lightning does the rest.”',
    idealShots: 1, threeStarTime: 60,
    map: board([['Z', -5, -1.5], ['T', 1, 2.5], ['D', 6, 2.5], ['m', 1, -1.5], ['#', -2, .5], ['#', -2, 1.5], ['#', 3, -1.5]]),
    mirrors: [{ x: 1, y: -1.5, angle: -.3, rotatable: true }],
  },
  {
    id: 'water-channel', name: 'The Voice of Water', lesson: '04 · CONDUCT',
    hint: 'Fire at the lower end of the channel. Water carries the charge and releases it along its edges.',
    mentor: '“Lightning finds paths where your eyes see only water.”',
    idealShots: 1, threeStarTime: 45,
    map: board([['Z', -5, -1.5], ['T', 2, 1.5], ['D', 6, 2.5], ['#', -3, -.5],
      ['~', -1, -1.5], ['~', -1, -.5], ['~', -1, .5], ['~', -1, 1.5]]),
    mirrors: [],
  },
  {
    id: 'water-branches', name: 'One Spark, Two Destinations', lesson: '05 · BRANCH',
    hint: 'Charge the channel with a single shot. Its outlets can reach both totems.',
    mentor: '“Shared strength can travel farther.”',
    idealShots: 1, threeStarTime: 45,
    map: board([['Z', -5, -1.5], ['T', -1, 2.5], ['T', 4, .5], ['D', 6, 2.5],
      ['#', -3, .5], ['#', 0, -.5], ['~', -1, -1.5], ['~', -1, -.5], ['~', -1, .5], ['~', 0, .5], ['~', 1, .5]]),
    mirrors: [],
  },
  {
    id: 'metal-route', name: 'The Metal Path', lesson: '06 · TRANSPORT',
    hint: 'Aim at the first bronze contact. The chain carries lightning to its open end.',
    mentor: '“Metal remembers the path shaped by its makers.”',
    idealShots: 1, threeStarTime: 45,
    map: board([['Z', -5, -1.5], ['T', 4, 1.5], ['D', 6, 2.5], ['#', -3, -.5],
      ['=', -1, -1.5], ['=', 0, -1.5], ['=', 1, -1.5], ['=', 1, -.5], ['=', 1, .5], ['=', 1, 1.5]]),
    metalPorts: [{ x: 1, y: 1.5, direction: { x: 1, y: 0 } }],
    mirrors: [],
  },
  {
    id: 'metal-fork', name: 'Where Paths Meet', lesson: '07 · CONNECT',
    hint: 'Fire at the entrance to the network. At each junction, the charge follows every branch.',
    mentor: '“When a path divides, lightning need not choose.”',
    idealShots: 1, threeStarTime: 50,
    map: board([['Z', -5, -.5], ['T', 4, 1.5], ['T', 4, -2.5], ['D', 6, 2.5],
      ['#', -3, .5], ['#', -3, -1.5], ['=', -1, -.5], ['=', 0, -.5], ['=', 1, -.5],
      ['=', 1, .5], ['=', 1, 1.5], ['=', 1, -1.5], ['=', 1, -2.5]]),
    metalPorts: [{ x: 1, y: 1.5, direction: { x: 1, y: 0 } }, { x: 1, y: -2.5, direction: { x: 1, y: 0 } }],
    mirrors: [],
  },
  {
    id: 'wood', name: 'The Patience of Fire', lesson: '08 · BURN',
    hint: 'One bolt burns the crate and is consumed. The next travels through the open path.',
    mentor: '“One spark prepares the way for the next.”',
    idealShots: 2, threeStarTime: 45,
    map: board([['Z', -5, -.5], ['T', 4, -.5], ['D', 6, 2.5],
      ...[-2.5, -1.5, -.5, .5, 1.5, 2.5].map(y => ['#', 0, y]), ['W', 0, -.5]]),
    mirrors: [],
  },
  {
    id: 'fragile', name: 'Opening a Breach', lesson: '09 · BREAK',
    hint: 'The block takes two hits to break. Save the third bolt for the totem.',
    mentor: '“Sometimes one attempt prepares the way for the next.”',
    idealShots: 3, threeStarTime: 50,
    map: board([['Z', -5, -.5], ['T', 4, -.5], ['D', 6, 2.5],
      ...[-2.5, -1.5, -.5, .5, 1.5, 2.5].map(y => ['#', 0, y]), ['B', 0, -.5]]),
    mirrors: [],
  },
  {
    id: 'clear-path', name: 'The Path You Leave', lesson: '10 · CLEAR A PATH',
    hint: 'Burn the crate, hit the block twice, then send the next bolt through the breach.',
    mentor: '“Lightning changes the world it travels through.”',
    idealShots: 4, threeStarTime: 60,
    map: board([['Z', -5, -.5], ['T', 4, -.5], ['D', 6, 2.5], ['W', -1, -.5],
      ...[-2.5, -1.5, -.5, .5, 1.5, 2.5].map(y => ['#', 1, y]), ['B', 1, -.5]]),
    mirrors: [],
  },
  {
    id: 'crystal', name: 'The Crystal Moment', lesson: '11 · SPLIT',
    hint: 'Aim at the crystal. Fire when its secondary arrow points toward the upper totem.',
    mentor: '“Timing is part of aiming, too.”',
    idealShots: 1, threeStarTime: 65,
    map: board([['Z', -5, -.5], ['G', 0, -.5], ['T', 4, -.5], ['T', 0, 1.5], ['D', 6, 2.5], ['#', -3, .5]]),
    crystals: [{ x: 0, y: -.5, period: 12, phase: Math.PI / 4 - Math.PI / 12 * (4.58 / 12) }],
    mirrors: [],
  },
  {
    id: 'charge-cloud', name: 'The Thunder That Waits', lesson: '12 · STORE',
    hint: 'Charge the light cloud. After the countdown, it releases lightning along its arrow.',
    mentor: '“Some forces grow while they seem to rest.”',
    idealShots: 1, threeStarTime: 45,
    map: board([['Z', -5, -.5], ['N', 0, -.5], ['T', 0, 2.5], ['D', 6, 2.5], ['#', -3, .5], ['#', -3, 1.5]]),
    clouds: [{ x: 0, y: -.5, delay: 1.4, direction: { x: 0, y: 1 } }], mirrors: [],
  },
  {
    id: 'cloud-trap', name: 'Choosing the Sky', lesson: '13 · AVOID TRAPS',
    hint: 'The dark cloud absorbs lightning. Aim at the light cloud above to take another path.',
    mentor: '“Not every cloud keeps what it receives.”',
    idealShots: 1, threeStarTime: 60,
    map: board([['Z', -5, -.5], ['C', -2, -.5], ['N', -2, 1.5], ['/', 4, 1.5], ['T', 4, -.5], ['D', 6, 2.5]]),
    clouds: [{ x: -2, y: 1.5, delay: 1.2, direction: { x: 1, y: 0 } }],
    mirrors: [{ x: 4, y: 1.5, angle: -Math.PI / 4, rotatable: false }],
  },
  {
    id: 'multi-hit', name: 'The Strength of Three Sparks', lesson: '14 · ACCUMULATE',
    hint: 'This totem needs three hits. Wait for each shot to finish before firing again.',
    mentor: '“Persistence can awaken stone.”',
    idealShots: 3, threeStarTime: 45,
    map: board([['Z', -5, -.5], ['T', 3, -.5], ['D', 6, 2.5]]),
    totems: [{ x: 3, y: -.5, hits: 3 }], mirrors: [],
  },
  {
    id: 'ordered', name: 'The Order of Thunder', lesson: '15 · FOLLOW THE ORDER',
    hint: 'Activate the totems 1 → 2 → 3. An out-of-order hit resets the sequence.',
    mentor: '“Before the great thunder, every note has its place.”',
    idealShots: 3, threeStarTime: 60,
    map: board([['Z', -5, -.5], ['T', 0, 1.5], ['T', 3, -.5], ['T', 0, -2.5], ['D', 6, 2.5]]),
    totems: [{ x: 0, y: 1.5, group: 'sequence', order: 1 }, { x: 3, y: -.5, group: 'sequence', order: 2 }, { x: 0, y: -2.5, group: 'sequence', order: 3 }],
    groups: [{ id: 'sequence', type: 'ordered' }], mirrors: [],
  },
  {
    id: 'timed', name: 'Before the Light Fades', lesson: '16 · RACE THE CLOCK',
    hint: 'Activate both totems within three seconds. You can line up your aim while the previous shot travels.',
    mentor: '“The bolt ends. Its echo can still wait for the next.”',
    idealShots: 2, threeStarTime: 45,
    map: board([['Z', -5, -.5], ['T', 1, 1.5], ['T', 1, -2.5], ['D', 6, 2.5]]),
    totems: [{ x: 1, y: 1.5, group: 'window' }, { x: 1, y: -2.5, group: 'window' }],
    groups: [{ id: 'window', type: 'timed', window: 3 }], mirrors: [],
  },
  {
    id: 'three-bounces', name: 'The Bronze Zigzag', lesson: '17 · THREE BOUNCES',
    hint: 'Set both blue mirrors. Lightning must rise, cross the wall, then head back down.',
    mentor: '“A path is found one turn at a time.”',
    idealShots: 1, threeStarTime: 90,
    map: board([['Z', -5, -1.5], ['m', -2, -1.5], ['/', -2, 1.5], ['m', 3, 1.5], ['T', 3, -1.5], ['D', 6, 2.5],
      ...[-2.5, -1.5, -.5, .5, 2.5].map(y => ['#', 0, y])]),
    mirrors: [{ x: -2, y: -1.5, angle: -.2, rotatable: true }, { x: -2, y: 1.5, angle: Math.PI / 4, rotatable: false }, { x: 3, y: 1.5, angle: .15, rotatable: true }],
  },
  {
    id: 'burn-and-bounce', name: 'The Labyrinth Breach', lesson: '18 · PREPARE THE PATH',
    hint: 'The first bolt burns the crate. Adjust the upper mirror so the second makes all three bounces.',
    mentor: '“Opening a path is not enough: you must give it direction.”',
    idealShots: 2, threeStarTime: 90,
    map: board([['Z', -5, -1.5], ['/', -2, -1.5], ['W', -2, .5], ['m', -2, 2.5], ['/', 3, 2.5], ['T', 3, -1.5], ['D', 6, 2.5],
      ...[-2.5, -1.5, -.5, .5, 1.5].map(y => ['#', 0, y])]),
    mirrors: [{ x: -2, y: -1.5, angle: Math.PI / 4, rotatable: false }, { x: -2, y: 2.5, angle: 0, rotatable: true }, { x: 3, y: 2.5, angle: -Math.PI / 4, rotatable: false }],
  },
  {
    id: 'cloud-cycle', name: 'The Pulse of the Sky', lesson: '19 · CYCLICK CLOUD',
    hint: 'This cloud releases every three seconds. Its clock does not start when charged: watch the cycle.',
    mentor: '“The sky has a rhythm of its own.”',
    idealShots: 1, threeStarTime: 60,
    map: board([['Z', -5, -.5], ['N', -1, -.5], ['/', -1, 2.5], ['T', 4, 2.5], ['D', 6, -2.5],
      ...[-2.5, -1.5, -.5, .5, 1.5].map(y => ['#', 1, y])]),
    clouds: [{ x: -1, y: -.5, period: 3, direction: { x: 0, y: 1 } }],
    mirrors: [{ x: -1, y: 2.5, angle: Math.PI / 4, rotatable: false }],
  },
  {
    id: 'cycle-crystal', name: 'A Meeting of Thunder', lesson: '20 · TWO CLOCKS',
    hint: 'Charge before the release at 3 s. The crystal must split lightning to the right and upward.',
    mentor: '“Arriving earlier or later can change everything.”',
    idealShots: 1, threeStarTime: 90,
    map: board([['Z', -5, -.5], ['N', -1, -.5], ['G', 2, -.5], ['T', 5, -.5], ['T', 2, 2.5], ['D', 6, 2.5],
      ...[-2.5, -1.5, .5, 1.5, 2.5].map(y => ['#', 0, y])]),
    clouds: [{ x: -1, y: -.5, period: 3, direction: { x: 1, y: 0 } }],
    crystals: [{ x: 2, y: -.5, period: 8, phase: Math.PI / 4 - Math.PI / 8 * (3 + (3 - .48005 - .42) / 12) }],
    mirrors: [],
  },
  {
    id: 'synchronized-clouds', name: 'Two Echoes, One Moment', lesson: '21 · SYNCHRONIZE BRANCHES',
    hint: 'Split toward both clouds. Their delays balance the travel times: activate both totems within half a second.',
    mentor: '“Two different paths can share one destination.”',
    idealShots: 1, threeStarTime: 90,
    map: board([['Z', -5, -.5], ['G', -2, -.5], ['N', 2, -.5], ['N', -2, 1.5], ['T', 2, 2.5], ['T', 4, 1.5], ['D', 6, 2.5],
      ...[-2.5, -1.5, .5, 2.5].map(y => ['#', 0, y])]),
    crystals: [{ x: -2, y: -.5, period: 12, phase: Math.PI / 4 - Math.PI / 12 * (2.58 / 12) }],
    clouds: [{ x: 2, y: -.5, delay: .9, direction: { x: 0, y: 1 } }, { x: -2, y: 1.5, delay: 1.1, direction: { x: 1, y: 0 } }],
    totems: [{ x: 2, y: 2.5, group: 'echoes' }, { x: 4, y: 1.5, group: 'echoes' }],
    groups: [{ id: 'echoes', type: 'timed', window: .5 }], mirrors: [],
  },
  {
    id: 'turn-during-charge', name: 'The Hands of Thunder', lesson: '22 · ROTATE WHILE WAITING',
    hint: 'Split upward. While the cloud charges, turn the blue mirror almost vertical to return lightning to the lower totem.',
    mentor: '“Waiting is also a time to act.”',
    idealShots: 1, threeStarTime: 100,
    map: board([['Z', -5, -1.5], ['G', -3, -1.5], ['m', -3, 1.5], ['N', 1, 1.5], ['N', 0, -1.5], ['T', 5, -1.5], ['T', 4, -2.5], ['D', 6, 2.5],
      ...[-2.5, .5, 1.5, 2.5].map(y => ['#', 2, y])]),
    crystals: [{ x: -3, y: -1.5, period: 12, phase: Math.PI / 4 - Math.PI / 12 * (1.58 / 12) }],
    clouds: [{ x: 0, y: -1.5, delay: 2.9, direction: { x: 1, y: 0 } }, { x: 1, y: 1.5, delay: 2, direction: { x: -1, y: 0 } }],
    mirrors: [{ x: -3, y: 1.5, angle: Math.PI / 4, rotatable: true }],
    totems: [{ x: 5, y: -1.5, group: 'hands' }, { x: 4, y: -2.5, group: 'hands' }],
    groups: [{ id: 'hands', type: 'timed', window: .45 }],
  },
  {
    id: 'ordered-bounces', name: 'The Melody of Bronze', lesson: '23 · ORDER THE BOUNCES',
    hint: 'The upper mirror directs the paths. Turn it between shots and activate the totems 1 → 2 → 3.',
    mentor: '“One piece can tell three stories.”',
    idealShots: 3, threeStarTime: 100,
    map: board([['Z', -5, -1.5], ['/', -2, -1.5], ['m', -2, 1.5], ['T', 3, 1.5], ['T', 2, -.5], ['T', -5, 1.5], ['D', 6, 2.5], ['#', -3, -.5], ['#', -3, .5],
      ...[-2.5, -1.5, -.5, 2.5].map(y => ['#', 0, y])]),
    mirrors: [{ x: -2, y: -1.5, angle: Math.PI / 4, rotatable: false }, { x: -2, y: 1.5, angle: .1, rotatable: true }],
    totems: [{ x: 3, y: 1.5, group: 'melody', order: 1 }, { x: 2, y: -.5, group: 'melody', order: 2 }, { x: -5, y: 1.5, group: 'melody', order: 3 }],
    groups: [{ id: 'melody', type: 'ordered' }],
  },
  {
    id: 'choose-your-route', name: 'The Return of Thunder', lesson: '24 · THE CLOUD RELAY',
    hint: 'Set both blue mirrors. Three bounces feed the clouds; their return lights the totem.',
    mentor: '“The clouds pass the spark between beats. Its return reveals the way.”',
    idealShots: 1, threeStarTime: 90,
    map: board([['Z', -6, -2.5], ['m', -4, -2.5], ['m', -4, 1.5], ['/', 1, 1.5], ['N', 1, -1.5], ['N', 5, -1.5], ['/', 5, 1.5], ['T', 1, 2.5], ['D', 6, 2.5],
      ['#', -5, -.5], ['#', 2, 2.5],
      ...[-2, -1, 0].flatMap(x => [['#', x, 2.5], ['#', x, .5]]),
      ...[-2.5, -1.5, -.5, .5, 2.5].map(y => ['#', -3, y]),
      ...[-2.5, -.5, .5, 2.5].map(y => ['#', 3, y])]),
    clouds: [{ x: 1, y: -1.5, period: 4, direction: { x: 1, y: 0 } },
      { x: 5, y: -1.5, period: 4, phase: 2, direction: { x: 0, y: 1 } }],
    mirrors: [{ x: -4, y: -2.5, angle: .1, rotatable: true }, { x: -4, y: 1.5, angle: -.1, rotatable: true },
      { x: 1, y: 1.5, angle: -Math.PI / 4, rotatable: false }, { x: 5, y: 1.5, angle: -Math.PI / 4, rotatable: false }],
  },
  {
    id: 'titans-gate', name: 'The Threshold of the Titan', lesson: '25 · MASTER THE THUNDER',
    hint: 'Burn, break and adjust. Useful releases: 3, 9, 15… s. Time between totems: 1.25 s.',
    mentor: '“Everything you have learned travels in this final spark.”',
    idealShots: 4, threeStarTime: 120,
    map: board([['Z', -5, -1.5], ['W', -3, -1.5], ['B', -1, -1.5], ['m', 1, -1.5], ['=', 1, .5], ['=', 1, 1.5], ['=', 2, 1.5], ['=', 3, 1.5], ['N', 4, 1.5], ['G', 4, -.5], ['T', 4, -2.5], ['m', -4, -.5], ['/', -4, 2.5], ['T', -1, 2.5], ['D', 6, 2.5],
      ...[-2.5, .5, 2.5].map(y => ['#', 0, y])]),
    mirrors: [{ x: 1, y: -1.5, angle: .1, rotatable: true }, { x: -4, y: -.5, angle: 0, rotatable: true }, { x: -4, y: 2.5, angle: Math.PI / 4, rotatable: false }],
    metalPorts: [{ x: 3, y: 1.5, direction: { x: 1, y: 0 } }],
    clouds: [{ x: 4, y: 1.5, period: 3, direction: { x: 0, y: -1 } }],
    crystals: [{ x: 4, y: -.5, period: 6, phase: Math.PI / 4 - Math.PI / 6 * (3 + (2 - .48005 - .42) / 12), incoming: { x: 0, y: -1 } }],
    totems: [{ x: 4, y: -2.5, group: 'titan' }, { x: -1, y: 2.5, group: 'titan' }],
    groups: [{ id: 'titan', type: 'timed', window: 1.25 }],
  },
  ...advancedLevels(board),
];
